sixth/shop/products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.products, name='category'),
    path('product/<int:pk>/', views.product, name='product'),
    path('products/page/<int:page>/', views.products, name='page'),
    path('products/basket-add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('products/basket-minus/<int:product_id>/', views.basket_minus, name='basket_minus'),
    path('products/basket-delete/<int:basket_id>/', views.basket_delete, name='basket_delete'),
]

sixth/shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sixth/shop/products/models.py
from django.db import models
from users.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Категория')
    description = models.TextField(blank=True, verbose_name="Описание категории")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категорию"
        verbose_name_plural = "категории"


class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name="Название товара")
    image = models.ImageField(upload_to="products_images/", blank=True, verbose_name="Изображение")
    description = models.TextField(blank=True, verbose_name="Описание")
    short_description = models.CharField(max_length=100, blank=True, verbose_name="Краткое описание")
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name="Категория")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"


class Photo(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Товар")
    add_photo = models.ImageField(upload_to="products_images/add/", blank=True, verbose_name="Фото")

    class Meta:
        verbose_name = "изображение"
        verbose_name_plural = "изображения"


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Клиент')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество товара')
    create_database = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f"Корзина для {self.user.username} | Продукт {self.product.name}"

    def sum(self):
        return self.quantity * self.product.price

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum())
        }
        return basket_item

    class Meta:
        verbose_name = 'товар в корзину'
        verbose_name_plural = 'корзина'

sixth/shop/products/views.py
from django.shortcuts import render, redirect
from .models import ProductCategory, Product, Basket
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required


def index(request):
    context = {
        'title': 'Market Place'
    }
    return render(request, "products/index.html", context)


def products(request, category_id=None):
    context = {
        'title': 'Market Place - Каталог',
        'categories': ProductCategory.objects.all(),
        # 'products': Product.objects.all()
    }
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()

    paginator = Paginator(products, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context.update({'products': page_obj})
    return render(request, "products/products.html", context)


def product(request, pk):
    product_obj = Product.objects.get(id=pk)
    context = {
        'title': product_obj.name,
        'product': product_obj,
        'categories': ProductCategory.objects.all()
    }
    return render(request, 'products/product.html', context)


@login_required(login_url='/users/login/')
def basket_add(request, product_id):
    current_page = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)
    if not baskets.exists():
        # Basket.objects.create(user=request.user, product=product, quantity=1)
        basket = Basket(user=request.user, product=product, quantity=1)
        basket.save()
        return redirect(current_page)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return redirect(current_page)


def basket_minus(request, product_id):
    current_page = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)
    if baskets.exists():
        basket = baskets.first()
        if basket.quantity > 1:
            basket.quantity -= 1
            basket.save()
        else:
            basket.delete()
        return redirect(current_page)


def basket_delete(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return redirect(request.META.get('HTTP_REFERER'))

sixth/shop/products/templates/products/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}{% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">{{ user.username }}
                        <i class="fas fa-user-circle"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'order-list' %}">Заказы <i class="fa fa-first-order"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

sixth/shop/products/templates/products/basket.html
{% load humanize %}

{% if baskets %}
<div class="col-lg-5">
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ basket.product.name }}</h5>
            <p class="card-text">{{ basket.product.short_description }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                <span class="text-muted">{{ basket.quantity }} шт.</span>
                <span class="text-muted">{{ basket.sum|intcomma }} руб.</span>
                <span class="text-muted">
                            <a href="{% url 'basket_add' basket.product.id  %}" style="text-decoration: none; color: gray;">
                                <i class="fas fa-cart-plus"></i>
                            </a>
                            <a href="{% url 'basket_minus' basket.product.id  %}" style="text-decoration: none; color: gray;">
                                <i class="fas fa-minus-square"></i>
                            </a>
                            <a href="{% url 'basket_delete' basket.id %}" style="text-decoration: none; color: gray;">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        </span>
            </li>
        </ul>
    </div>
    {% endfor %}

    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ total_sum|intcomma }} руб.</h4>
        </div>
    </div>
    <a href="{% url 'order-create' %}" class="btn btn-success btn-lg float-right">Оформить</a>
</div>
{% else %}
<div class="col-lg-5">
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
</div>
{% endif %}

sixth/shop/products/templates/products/category.html
<div class="list-group">
    <a href="{% url 'products' %}" class="list-group-item">Все категории</a>
    {% for category in categories %}
    <a href="{% url 'category' category.id %}" class="list-group-item">{{ category.name }}</a>
    {% endfor %}
</div>

sixth/shop/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}

<!-- Page Content -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <img src="{% static 'vendor/img/icon.png' %}" alt="" width="300">
                <p>
                    Новые образы и лучшие бренды Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>

{% endblock %}

sixth/shop/products/templates/products/product.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            {% include 'products/category.html' %}

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
			<div class="row">
                <div class="col-lg-5" >
                    <img src="{{ product.image.url }}" alt="" class="big">
                    <br>
                    <div class="center">
                        {% for img in product.photo_set.all %}
                        <img src="{{ img.add_photo.url }}" alt="" class="small">
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-7">
                    <h1 class="title">{{ product.name }}</h1>
                    <h4>{{ product.short_description }}</h4>
                    <h2 class="price">{{ product.price|intcomma }} руб.</h2>

                    <a href="{% url 'basket_add' product.id %}" class="btn btn-outline-success  basket">Отправить в корзину</a>
<!--                    <h4 class="basket"><a href="#">В КОРЗИНУ</a></h4>-->
                    <h5 class="quantity">В наличии: {{ product.quantity }} шт.</h5>
                    <div>
					{{ product.description|safe }}
					</div>
                </div>
            </div>           

        </div>

    </div>

</div>
<!-- /.container -->


{% endblock %}

sixth/shop/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            {% include 'products/category.html' %}

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">

                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="{% url 'product' product.id %}">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{% url 'product' product.id %}">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price|intcomma }} руб.</h5>
                            <p class="card-text">{{ product.short_description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="{% url 'basket_add' product.id %}" class="btn btn-outline-success">Отправить в корзину</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

            {% if products %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">

                    {% if products.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    {% endif %}

                    {% if products.has_other_pages %}
                    {% for page in products.paginator.page_range %}
                    <li class="page-item {% if page == products.number %} active {% endif %}"><a class="page-link" href="?page={{ page }}">{{ page}}</a></li>
                    {% endfor %}
                    {% endif %}

                    {% if products.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}

        </div>

    </div>

</div>
<!-- /.container -->
{% endblock %}